name: Firmwire-CI

on:
  schedule:
    - cron: 30 22 * * *
  workflow_dispatch:
    
  release:
    types: [published]

jobs:

  build_firmware:

    name: Build Firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    
      - name: Fix up git URLs
        run: |
         git config --global --add url."https://${{ secrets.GITHUB_SECRET }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
         git config --global --add url."https://${{ secrets.GITHUB_SECRET }}:x-oauth-basic@github.com/".insteadOf "git@github.com:"
      
      - name: Install Dependencies
        run: |
          sudo -E apt-get update
          sudo -E apt-get -fy install bison flex swig lzop lzma libmpc-dev u-boot-tools libncurses5-dev build-essential asciidoc binutils bzip2 gawk gettext git libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion uglifyjs p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf
      
      - name: Generate artifact Path
        run: |
          mkdir ./artifact
          sudo chmod 777 ./artifact
          cd ./artifact
          echo ${PWD}
          
      - name: Path Init
        run: |
          cd ./artifact
          
          if [ ! -d "bootloader" ];then
            mkdir bootloader
          fi

          if [ ! -d "kernelfile" ];then
            mkdir kernelfile
          fi

          if [ ! -d "rootfs" ];then
            mkdir rootfs
          fi
          
          ls -l
          
      - name: U-Boot Compile
        run: |
          wget -c https://releases.linaro.org/components/toolchain/binaries/6.5-2018.12/arm-linux-gnueabihf/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz
          tar -xf gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz
          export CC=`pwd`/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-
          ${CC}gcc --version

          export ARCH=arm CROSS_COMPILE=${CC}

          git clone -b v2022.04-rc1 https://github.com/u-boot/u-boot/ --depth=1
          cd u-boot


          make distclean
          make stm32mp15_basic_defconfig
          make DEVICE_TREE=stm32mp157a-dk1 all -j $(nproc)

      - name: Copy U-Boot files
        run: |
          cp ./u-boot/u-boot-spl.stm32 ./artifact/bootloader/u-boot-spl.stm32
          cp ./u-boot/u-boot.img ./artifact/bootloader/u-boot.img
          
          cd ..
          rm -rf ./u-boot
          ls -l
          

      - name: Deliver U-Boot
        uses: actions/upload-artifact@v2
        with:
          name: STM32MP157_bootloader
          path: ./artifact/bootloader/

      - name: Deliver Kernel
        uses: actions/upload-artifact@v2
        with:
          name: STM32MP157_kernel
          path: ./artifact/kernelfile/

      - name: Deliver rootfs
        uses: actions/upload-artifact@v2
        with:
          name: STM32MP157_rootfs
          path: ./artifact/rootfs/

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/*
          tag: ${{ github.ref }}
          file_glob: true
