name: Firmwire-CI

on:
  schedule:
    - cron: 0 20 * * *
  release:
    types: [published]

jobs:

  build_firmware:

    name: Build Firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get update
          sudo -E apt-get -y install gcc-arm-linux-gnueabihf build-essential asciidoc bison flex swig binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler lzop lzma libmpc-dev u-boot-tools libncurses5-dev antlr3 gperf
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h
          
          if [ -f "u-boot" ];then
            rm -rf ./u-boot/*
          fi

          if [ -f "armv7-lpae-multiplatform" ];then
            rm -rf ./armv7-lpae-multiplatform/*
          fi

          if [ ! -d "bootloader" ];then
            mkdir bootloader
          else 
            rm -rf bootloader
            mkdir bootloader
          fi

          if [ ! -d "kernelfile" ];then
            mkdir kernelfile
          else 
            rm -rf kernelfile
            mkdir kernelfile
          fi

          export ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-


          sudo apt install 
          git clone -b v2022.04-rc1 https://github.com/u-boot/u-boot/ --depth=1
          cd u-boot


          make distclean
          make stm32mp15_basic_defconfig
          make DEVICE_TREE=stm32mp157a-dk1 all -j $(nproc)


          cp ./u-boot-spl.stm32 ../bootloader/u-boot-spl.stm32
          cp ./u-boot.img ../bootloader/u-boot.img

          cd ..
          rm -rf u-boot


          git clone https://github.com/RobertCNelson/armv7-lpae-multiplatform
          cd armv7-lpae-multiplatform/
          git checkout origin/v5.16.x -b tmp
          sed -i "s/git.kernel.org\/pub\/scm\/linux\/kernel\/git\/stable/mirrors.tuna.tsinghua.edu.cn\/git/g" ./scripts/git.sh
          ./build_kernel.sh

          export kernel_version=5.16.9-armv7-lpae-x13

          sudo cp ./deploy/${kernel_version}.zImage ../kernelfile/${kernel_version}.zImage
          sudo cp ./deploy/${kernel_version}-dtbs.tar.gz ../kernelfile/${kernel_version}-dtbs.tar.gz
          sudo cp ./deploy/${kernel_version}-modules.tar.gz ../kernelfile/${kernel_version}-modules.tar.gz

          cd ..
          rm -rf armv7-lpae-multiplatform

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
